let aliases: [String:String] = [
    "pick up":"take",
]

let lexicon: [String:Set<PhrasalCategory>] = [
    "look":[Verb("look")],
    //"examine":[Verb],
    //"glance":[Verb],
    "read":[Verb("read")],
    //"save":[Verb],
    //"restore":[Verb],
    "quit":[Verb("quit")],
    //"restart":[Verb],
    "take":[Verb("take")],
    "get":[Verb("take")],
    "drop":[Verb("drop")],
    "transfer":[Verb("transfer")],
    "go":[Verb("go")],
    "move":[Verb("go"), Verb("transfer")],
    "open":[Verb("open"), Adjective("open", applyingFilter: { $0.attributes.contains("open") })],
    "close":[Verb("close")],
    "insert":[Verb("insert")],
    "put":[Verb("insert")],
    //"push":[Verb],
    //"pull":[Verb],
    //"turn":[Verb],
    //"feel":[Verb],
    //"eat":[Verb],
    //"drink":[Verb],
    //"smell":[Verb],
    //"listen":[Verb],
    //"climb":[Verb],
    //"break":[Verb],
    //"burn":[Verb],
    //"lock":[Verb("lock"), Noun("lock")],
    "unlock":[Verb("unlock")],
    //"wave":[Verb],
    //"wear":[Verb],
    //"dig":[Verb],
    "enter":[Verb("enter")],
    "exit":[Verb("exit"), Verb("quit")],
    //"search":[Verb],
    //"jump":[Verb],
    //"say":[Verb],
    //"yell":[Verb],
    //"whisper":[Verb],
    //"tell":[Verb],
    //"show":[Verb],
    //"help":[Verb, Noun],
    //"give":[Verb],
    //"kill":[Verb],
    //"attack":[Verb],
    //"kiss":[Verb],
    //"knock":[Verb],
    //"lick":[Verb],
    //"remove":[Verb],
    //"sit":[Verb],
    //"sleep":[Verb],
    //"wait":[Verb],
    //"taste":[Verb],
    "throw":[Verb("throw")],
    //"toss":[Verb],
    //"tie":[Verb, Noun],
    //"untie":[Verb],
    //"touch":[Verb],
    //"prod":[Verb],
    //"poke":[Verb],
    //"nudge":[Verb],
    //"blow":[Verb],
    //"buy":[Verb],
    //"cut":[Verb],
    //"rub":[Verb],
    //"wake":[Verb],
    //"swim":[Verb],
    //"squeeze":[Verb],
    //"crush":[Verb],
    //"mash":[Verb],
    //"set":[Verb],
    //"is":[Verb],
    
    "red":[Adjective("red", applyingFilter: { $0.attributes.contains("red") })],
    "green":[Adjective("green", applyingFilter: { $0.attributes.contains("green") })],
    "blue":[Adjective("blue", applyingFilter: { $0.attributes.contains("blue") })],
    "yellow":[Adjective("yellow", applyingFilter: { $0.attributes.contains("yellow") })],
    "orange":[Adjective("orange", applyingFilter: { $0.attributes.contains("orange") })/*, Noun("orange")*/],
    "purple":[Adjective("purple", applyingFilter: { $0.attributes.contains("purple") })],
    "violet":[Adjective("purple", applyingFilter: { $0.attributes.contains("purple") })],
    "brown":[Adjective("brown", applyingFilter: { $0.attributes.contains("brown") })],
    "silver":[Adjective("silver", applyingFilter: { $0.attributes.contains("silver") })/*, Noun("silver")*/],
    "gold":[Adjective("gold", applyingFilter: { $0.attributes.contains("gold") })/*, Noun("gold")*/],
    "golden":[Adjective("gold", applyingFilter: { $0.attributes.contains("gold") })],
    "white":[Adjective("white", applyingFilter: { $0.attributes.contains("white") })],
    "black":[Adjective("black", applyingFilter: { $0.attributes.contains("black") })],
    "light":[Adjective("light", applyingFilter: { $0.attributes.contains("light") }), Verb("light")],
    "dark":[Adjective("dark", applyingFilter: { $0.attributes.contains("dark") })],
    "clear":[Adjective("transparent", applyingFilter: { $0.attributes.contains("transparent") }), Verb("clear")],
    "transparent":[Adjective("transparent", applyingFilter: { $0.attributes.contains("transparent") })],
    "transluscent":[Adjective("transparent", applyingFilter: { $0.attributes.contains("transparent") })],
    //"new":[Adjective],
    //"old":[Adjective],
    //"big":[Adjective],
    //"large":[Adjective],
    //"small":[Adjective],
    //"little":[Adjective],
    //"young":[Adjective],
    //"long":[Adjective],
    //"tall":[Adjective],
    //"broad":[Adjective],
    //"short":[Adjective],
    //"only":[Adjective],
    //"strong":[Adjective],
    //"sturdy":[Adjective],
    //"weak":[Adjective],
    //"dead":[Adjective],
    //"best":[Adjective],
    //"worst":[Adjective],
    //"strongest":[Adjective],
    //"weakest":[Adjective],
    //"oldest":[Adjective],
    //"newest":[Adjective],
    //"most":[Adjective],
    //"closed":[Adjective("closed")],
    
    //"not":[Adverb],???
    
    "up":[Preposition("up")],
    "down":[Preposition("down")],
    "north":[Preposition("north")],
    "south":[Preposition("south")],
    "east":[Preposition("east")],
    "west":[Preposition("west")],
    "northwest":[Preposition("northwest")],
    "northeast":[Preposition("northeast")],
    "southwest":[Preposition("southwest")],
    "southeast":[Preposition("southeast")],
    "in":[Preposition("in")],
    "above":[Preposition("above")],
    "below":[Preposition("below")],
    "at":[Preposition("at")],
    "to":[Preposition("to")],
    "from":[Preposition("from")],
    //"left":[Preposition],
    //"right":[Preposition],
    "on":[Preposition("on"), Adverb("on"), Adjective("on", applyingFilter: { $0.attributes.contains("on") })],
    "of":[Preposition("of")],
    //"about":[Preposition],
    //"around":[Preposition],
    //"except":[Preposition],
    //"with":[Preposition],
    //"using":[Preposition],
    
    "the":[Determiner("the", applyingRestriction: { if $0.count == 1 { return $0 } else { throw EvaluationError.DeterminerDidNotMatch(determiner: "the", didNotMatch: $0) } })],
    "a":[Determiner("a", applyingRestriction: { if $0.isEmpty { throw EvaluationError.DeterminerDidNotMatch(determiner: "a", didNotMatch: $0) } else { return [$0.first!] } })],
    "an":[Determiner("an", applyingRestriction: { if $0.isEmpty { throw EvaluationError.DeterminerDidNotMatch(determiner: "a", didNotMatch: $0) } else { return [$0.first!] } })],
    //"that":[Determiner("that"), Conjunction("that")],
    //"my":[Determiner("my")],
    "all":[Determiner("all", applyingRestriction: { $0 })],
    
    "and":[Conjunction("and")],
    "but":[Conjunction("but")],
    "then":[Conjunction("then")],
    
    "everything":[Noun("everything", applyingSelector: { $0 })],
    "inventory":[Noun("inventory", applyingSelector: { $0 })], // dummy function, "take inventory" is handled separately
    
    // SIMPLIFICATIONS
    // already parsed shortened versions of some common commands
    
    "n":[RegularVerbPhrase(withVerb: Verb("go"), withPrepositionalPhrase: RegularPrepositionalPhrase(withPreposition: Preposition("north")))],
    "s":[RegularVerbPhrase(withVerb: Verb("go"), withPrepositionalPhrase: RegularPrepositionalPhrase(withPreposition: Preposition("south")))],
    "e":[RegularVerbPhrase(withVerb: Verb("go"), withPrepositionalPhrase: RegularPrepositionalPhrase(withPreposition: Preposition("east")))],
    "w":[RegularVerbPhrase(withVerb: Verb("go"), withPrepositionalPhrase: RegularPrepositionalPhrase(withPreposition: Preposition("west")))],
    "u":[RegularVerbPhrase(withVerb: Verb("go"), withPrepositionalPhrase: RegularPrepositionalPhrase(withPreposition: Preposition("up")))],
    "d":[RegularVerbPhrase(withVerb: Verb("go"), withPrepositionalPhrase: RegularPrepositionalPhrase(withPreposition: Preposition("down")))],
    "i":[RegularVerbPhrase(withVerb: Verb("take"), withNounPhrase: RegularNounPhrase(withNoun: Noun("inventory", applyingSelector: { $0 })))],
    "l":[RegularVerbPhrase(withVerb: Verb("look"))]
    
    // and some things (nouns) for testing ---------------------
    
    //"inventory":[Noun("inventory", applyingSelector: {})],
    //"self":[Noun("self")],
    //"pick":[Noun("pickaxe"), Verb("unlock")],
    //"broom":[Noun("broom")],
    //"room":[Noun("room")],
    //"door":[Noun("door", applyingSelector: {$0 is Door})],
    //"chair":[Noun("chair")],
    //"me":[Noun("me")],
    //"egg":[Noun("egg")],
    //"pan":[Noun("pan")],
    //"spoon":[Noun("spoon")],
    //"fork":[Noun("fork")],
    //"knife":[Noun("knife")],
    //"sword":[Noun("sword")],
    //"longsword":[Noun("longsword")],
    //"bow":[Noun("bow")],
    //"longbow":[Noun("longbow")],
    //"mary":[Noun("mary")],
    //"foe":[Noun("foe")]
    
    // some more specfic things for testing edge cases --------
    
    
]