let lexicon: [String: Set<LexicalCategory>] = [
    //"look":[Verb],
    //"examine":[Verb],
    //"glance":[Verb],
    //"read":[Verb],
    //"save":[Verb],
    //"restore":[Verb],
    //"quit":[Verb],
    //"restart":[Verb],
    "take":[Verb("take")],
    "get":[Verb("take")],
    "drop":[Verb("drop")],
    //"transfer":[Verb],
    "go":[Verb("go")],
    "move":[Verb("go")],
    //"open":[Verb, Adjective],
    //"close":[Verb],
    //"put":[Verb],
    //"push":[Verb],
    //"pull":[Verb],
    //"turn":[Verb],
    //"feel":[Verb],
    //"eat":[Verb],
    //"drink":[Verb],
    //"smell":[Verb],
    //"listen":[Verb],
    //"climb":[Verb],
    //"break":[Verb],
    //"burn":[Verb],
    //"lock":[Verb, Noun],
    //"unlock":[Verb],
    //"wave":[Verb],
    //"wear":[Verb],
    //"dig":[Verb],
    //"enter":[Verb],
    //"exit":[Verb],
    //"go":[Verb],
    //"search":[Verb],
    //"jump":[Verb],
    //"say":[Verb],
    //"whisper":[Verb],
    //"tell":[Verb],
    //"show":[Verb],
    //"help":[Verb, Noun],
    //"give":[Verb],
    //"kill":[Verb],
    //"attack":[Verb],
    //"kiss":[Verb],
    //"knock":[Verb],
    //"lick":[Verb],
    //"remove":[Verb],
    //"sit":[Verb],
    //"sleep":[Verb],
    //"wait":[Verb],
    //"taste":[Verb],
    "throw":[Verb("throw")],
    //"toss":[Verb],
    //"tie":[Verb, Noun],
    //"untie":[Verb],
    //"touch":[Verb],
    //"prod":[Verb],
    //"poke":[Verb],
    //"nudge":[Verb],
    //"blow":[Verb],
    //"buy":[Verb],
    //"cut":[Verb],
    //"rub":[Verb],
    //"wake":[Verb],
    //"swim":[Verb],
    //"squeeze":[Verb],
    //"crush":[Verb],
    //"mash":[Verb],
    //"set":[Verb],
    //"is":[Verb],
    
    //"red":[Adjective],
    //"green":[Adjective],
    //"blue":[Adjective],
    //"yellow":[Adjective],
    //"orange":[Adjective, Noun],
    //"purple":[Adjective],
    //"violet":[Adjective],
    //"brown":[Adjective],
    //"silver":[Adjective, Noun],
    //"gold":[Adjective, Noun],
    //"golden":[Adjective],
    //"white":[Adjective],
    //"black":[Adjective],
    //"light":[Adjective, Verb],
    //"dark":[Adjective],
    //"clear":[Adjective, Verb],
    //"transparent":[Adjective],
    //"new":[Adjective],
    //"old":[Adjective],
    //"big":[Adjective],
    //"large":[Adjective],
    //"small":[Adjective],
    //"little":[Adjective],
    //"young":[Adjective],
    //"long":[Adjective],
    //"tall":[Adjective],
    //"broad":[Adjective],
    //"short":[Adjective],
    //"only":[Adjective],
    //"strong":[Adjective],
    //"weak":[Adjective],
    //"dead":[Adjective],
    //"best":[Adjective],
    //"worst":[Adjective],
    //"strongest":[Adjective],
    //"weakest":[Adjective],
    //"most":[Adjective],
    
    //"not":[Adverb],???
    
    "up":[Preposition("up")],
    "down":[Preposition("down")],
    "north":[Preposition("north")],
    "south":[Preposition("south")],
    "east":[Preposition("east")],
    "west":[Preposition("west")],
    "in":[Preposition("in")],
    "above":[Preposition("above")],
    "below":[Preposition("below")],
    "at":[Preposition("at")],
    "to":[Preposition("to")],
    "from":[Preposition("from")],
    //"left":[Preposition],
    //"right":[Preposition],
    //"on":[Preposition, Adverb, Adjective],
    //"of":[Preposition],
    //"about":[Preposition],
    //"around":[Preposition],
    //"except":[Preposition],
    //"with":[Preposition],
    
    //"the":[Determiner],
    //"a":[Determiner],
    //"an":[Determiner],
    //"that":[Determiner, Conjunction],
    //"my":[Determiner],
    
    //"and":[Conjunction],
    //"but":[Conjunction],
    
    // and some things (nouns) for testing
    
    //"inventory":[Noun],
    //"self":[Noun],
    //"pick":[Noun],
    //"broom":[Noun],
    //"room":[Noun],
    //"door":[Noun],
    //"chair":[Noun],
    //"me":[Noun],
    //"egg":[Noun],
    //"pan":[Noun],
    //"spoon":[Noun],
    //"fork":[Noun],
    //"knife":[Noun],
    //"sword":[Noun],
    //"longsword":[Noun],
    //"bow":[Noun],
    //"longbow":[Noun],
    //"mary":[Noun],
    "foe":[Noun("foe")]
]

////////////////////////////////////////////////////////////////
// REFERENCE BY CATEGORY
////////////////////////////////////////////////////////////////